# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [130]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [131]:
print("NUMPY version:", np.__version__)
np.show_config()


NUMPY version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4347739648
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_a51i_mbs7m/croot/numpy_and_numpy_base_1708638620867/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdebug-prefix-map=/opt/anac

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [132]:
#First way
a = np.random.rand(2, 3, 5)
#Second way
a = np.random.random((2, 3, 5))
#Third way
a = np.random.random_sample((2, 3, 5))



### 4. Print a.


In [133]:
print(a)


[[[0.74564632 0.67276353 0.55169353 0.30544789 0.75057735]
  [0.54245683 0.22444819 0.2593299  0.30920373 0.44776237]
  [0.96949817 0.16169326 0.90965469 0.6262231  0.85490264]]

 [[0.35915062 0.91623444 0.90355992 0.02832135 0.19275248]
  [0.08241592 0.11360071 0.62536147 0.72485845 0.70110636]
  [0.42352828 0.5835019  0.81903238 0.62207164 0.51311866]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [134]:
b = np.ones((5, 2, 3))



### 6. Print b.


In [135]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [136]:
#Before comparing the sizes of a and b, we should first understand their dimensions.
print(a.shape) #Dimension of a
print(b.shape) #Dimension of b

#In numpy size means the total number of elements. So for a, it should be 2*3*5 and for b it should be 5*2*3
#To answer "Do a and b have the same size", we use the comparison operator (==)
print(a.size == b.size)


(2, 3, 5)
(5, 2, 3)
True



### 8. Are you able to add a and b? Why or why not?


In [137]:
print(a.shape)
print(b.shape)

# The shapes are different and are not compatible for broadcasting,
# so a and b cannot be added directly.

(2, 3, 5)
(5, 2, 3)




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [138]:
c = np.transpose(b,(1, 2, 0))
print(c.shape)

(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [139]:
d = a + c
print(d)

# It works because a and c have the same shape (2, 3, 5),
# so NumPy can perform element-wise addition.


[[[1.74564632 1.67276353 1.55169353 1.30544789 1.75057735]
  [1.54245683 1.22444819 1.2593299  1.30920373 1.44776237]
  [1.96949817 1.16169326 1.90965469 1.6262231  1.85490264]]

 [[1.35915062 1.91623444 1.90355992 1.02832135 1.19275248]
  [1.08241592 1.11360071 1.62536147 1.72485845 1.70110636]
  [1.42352828 1.5835019  1.81903238 1.62207164 1.51311866]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [140]:
print(a)
print(d)
#Each value in d is 1 greater than the corresponding value in a. 
# This is because c contains only ones, so adding a + c adds 1 to every element of a.
#To prove this relationship, I run the code below and should have 1s
print(d-a)



[[[0.74564632 0.67276353 0.55169353 0.30544789 0.75057735]
  [0.54245683 0.22444819 0.2593299  0.30920373 0.44776237]
  [0.96949817 0.16169326 0.90965469 0.6262231  0.85490264]]

 [[0.35915062 0.91623444 0.90355992 0.02832135 0.19275248]
  [0.08241592 0.11360071 0.62536147 0.72485845 0.70110636]
  [0.42352828 0.5835019  0.81903238 0.62207164 0.51311866]]]
[[[1.74564632 1.67276353 1.55169353 1.30544789 1.75057735]
  [1.54245683 1.22444819 1.2593299  1.30920373 1.44776237]
  [1.96949817 1.16169326 1.90965469 1.6262231  1.85490264]]

 [[1.35915062 1.91623444 1.90355992 1.02832135 1.19275248]
  [1.08241592 1.11360071 1.62536147 1.72485845 1.70110636]
  [1.42352828 1.5835019  1.81903238 1.62207164 1.51311866]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 12. Multiply a and c. Assign the result to e.


In [141]:
e = a*c
print(e)

[[[0.74564632 0.67276353 0.55169353 0.30544789 0.75057735]
  [0.54245683 0.22444819 0.2593299  0.30920373 0.44776237]
  [0.96949817 0.16169326 0.90965469 0.6262231  0.85490264]]

 [[0.35915062 0.91623444 0.90355992 0.02832135 0.19275248]
  [0.08241592 0.11360071 0.62536147 0.72485845 0.70110636]
  [0.42352828 0.5835019  0.81903238 0.62207164 0.51311866]]]




### 13. Does e equal to a? Why or why not?


In [142]:
np.array_equal(e, a)
# Yes, e equals a because c contains only 1s.
# Multiplying by 1 leaves every value unchanged.

True



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [143]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("Maximun: ", d_max)
print("Minimun: ", d_min)
print("Mean: ", d_mean)


Maximun:  1.96949817294909
Minimun:  1.0283213545455856
Mean:  1.5313305355850066


In [144]:
#Another route
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print("Maximun: ", d_max)
print("Minimun: ", d_min)
print("Mean: ", d_mean)

Maximun:  1.96949817294909
Minimun:  1.0283213545455856
Mean:  1.5313305355850066



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [145]:
#Creating an empty array
f = np.empty(d.shape)
print(f.shape)


(2, 3, 5)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [146]:
#Because d is 3-dimensional, we can use three loops
# Go through each block in d
for block in range(d.shape[0]):

    # Go through each block in d
    for row in range(d.shape[1]):

        # Go through each column in the current row
        for column in range(d.shape[2]):

            # Get the value at the current position
            value = d[block, row, column]

            # If the value is equal to d_min, assign 0 to that
            if value == d_min:
                f[block, row, column] = 0

            # If the value is less than d_mean, assign 25 to that
            elif value < d_mean:
                f[block, row, column] = 25

            # If the value is equal to d_mean, assign 50 to that
            elif value == d_mean:
                f[block, row, column] = 50

            # If the value is less than d_max, assign 75 to that
            elif value < d_max:
                f[block, row, column] = 75

            # Otherwise it must be the maximum, assign 100 to that 
            else:
                f[block, row, column] = 100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [147]:
print(d)
print(f)
# The result is as expected.
# Values are labelled according to their position relative
# to the minimum, mean, and maximum of d.

[[[1.74564632 1.67276353 1.55169353 1.30544789 1.75057735]
  [1.54245683 1.22444819 1.2593299  1.30920373 1.44776237]
  [1.96949817 1.16169326 1.90965469 1.6262231  1.85490264]]

 [[1.35915062 1.91623444 1.90355992 1.02832135 1.19275248]
  [1.08241592 1.11360071 1.62536147 1.72485845 1.70110636]
  [1.42352828 1.5835019  1.81903238 1.62207164 1.51311866]]]
[[[ 75.  75.  75.  25.  75.]
  [ 75.  25.  25.  25.  25.]
  [100.  25.  75.  75.  75.]]

 [[ 25.  75.  75.   0.  25.]
  [ 25.  25.  75.  75.  75.]
  [ 25.  75.  75.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [148]:
# Create an empty array g with the same shape as d
# Store strings in this array
g = np.empty(d.shape, dtype=str)

# Go through each block in d
for block in range(d.shape[0]):

    # Go through each row in the current block
    for row in range(d.shape[1]):

         # Go through each column in the current row
        for column in range(d.shape[2]):

            # Get the value at the current position
            value = d[block, row, column]

              # If the value is the minimum, label it A
            if d[block, row, column] == d_min:
                g[block, row, column] = "A"

            # If the value is between the minimum and the mean, label it B
            elif d[block, row, column] < d_mean:
                g[block, row, column] = "B"

            # If the value equals the mean, label it C
            elif d[block, row, column] == d_mean:
                g[block, row, column] = "C"

            # If the value is between the mean and the maximum, label it D
            elif d[block, row, column] < d_max:
                g[block, row, column] = "D"

            # Otherwise it must be the maximum, so label it E
            else:
                g[block, row, column] = "E"
print(g)

[[['D' 'D' 'D' 'B' 'D']
  ['D' 'B' 'B' 'B' 'B']
  ['E' 'B' 'D' 'D' 'D']]

 [['B' 'D' 'D' 'A' 'B']
  ['B' 'B' 'D' 'D' 'D']
  ['B' 'D' 'D' 'D' 'B']]]
